server:
  port: 8088
spring:
  application:
    name: base
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
       register: false
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    serviceUrl:
#      defaultZone: http://127.0.0.1:7001/eureka/
#eureka-client:
#  ribbon:
#    listOfServers: 127.0.0.1:8001
feign:
  hystrix:
    enabled: true