server:
  port: 8088
spring:
  application:
    name: base
ribbon:
  eureka:
    enabled: false
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:7001/eureka/
service-sayHello:
  ribbon:
    listOfServers: http://${eureka.instance.hostname}:8001