server:
  port: 8088
spring:
  application:
    name: base
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:7001/eureka/
eureka-client:
  ribbon:
    #NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    listOfServers: 127.0.0.1:8001