server:
 port: 8888
spring:
  cloud:
    bus:
      refresh:
        enabled: true
    config:
      server:
        git:
          uri: https://github.com/mexyz/config
          basedir: target/config
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh,bus-env
